// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwovptlzsufngwkrwwyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3b3ZwdGx6c3Vmbmd3a3J3d3lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNDg1MjcsImV4cCI6MjA2NDkyNDUyN30.hPPIGIHaD94puiskwBynNKMPAmE3-HFjPK__9NkFPjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);